version: '3.8'

services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./sites:/var/www
      - ./nginx/site1.conf:/etc/nginx/conf.d/site1.conf
      - ./nginx/site2.conf:/etc/nginx/conf.d/site2.conf
      - ./nginx/roberson.conf:/etc/nginx/conf.d/roberson.conf
      - ./nginx/voleonline.conf:/etc/nginx/conf.d/voleonline.conf
    depends_on:
      - php

  php:
    build: ./php
    volumes:
      - ./sites:/var/www
    env_file:
      - .env

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - db
    volumes:
      - ./adminer/adminer.css:/var/www/html/adminer.css

volumes:
  pgdata:
